### ISSUE TITLE
Add image release notes to RSS feed

### ISSUE THREAD

**Issue by Mascherino** [thebigbone/docker-rss#6]
While I don't have a use for this project in its current form (I'm already using whats up docker for update checking), I think receiving image release / updates notes as a RSS feed would be great. I imagine it could work similar to the release notes template link whats up docker is using. The user would have to specify the page (most likely something like a github link) where update notes get posted for each image (so something like a new environment variable for each container you want to receive updates from). Docker-RSS would parse the newest update (if different from the currently installed image) and post it to the RSS feed.

Something like this:
````yaml
services:
  traefik:
    image: traefik:v3.2.5
    container_name: traefik
    environment:
      # would link to https://github.com/traefik/traefik/releases/tag/v3.3.3 as v3.3.3 is the newest release
      - docker-rss.release.link=https://github.com/traefik/traefik/releases/tag/v{major}.{minor}.{patch} 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ````
Next time docker-rss checks for updates, it recognizes traefik is out of date (current version is v3.3.3), checks the user supplied page, parses the newest post there and posts that on the RSS feed.

Unfortunately that would only work with images that actually do releases (and use some kind of semantic version) and not just update every time a commit is done.
